Problem Statement 1:


 Write a function so that the columns of the output matrix are powers of the input 
 vector. 
 
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1. 
 
 
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde. 

In [1]:
import numpy as np

In [2]:
#vander_matrix_generator function
def vander_matrix_generator(ipvector, n, increasing):
    
    if not increasing:
        op_matx = np.array([x**(n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif increasing:
        op_matx = np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    
    return op_matx

In [3]:
#Getting inputs from User
ip_vector = input("Enter the input vector : ")
input_vector = np.fromstring(ip_vector, dtype=int, sep=',')
op_col_no = int(input("Number of columns in output matrix : "))

#Computing Vander Matrix from Inputs received in both increasing and decresing order
op_matrix_dec_order = vander_matrix_generator(input_vector, op_col_no, False)
op_matrix_inc_order = vander_matrix_generator(input_vector, op_col_no, True)

#Printing the output
print("\nVander matrix of the input array in decreasing order of powers:\n",op_matrix_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n",op_matrix_inc_order,"\n")

Enter the input vector : 1,2,3,4,5
Number of columns in output matrix : 4

Vander matrix of the input array in decreasing order of powers:
 [[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]] 

Vander matrix of the input array in increasing order of powers:
 [[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]] 



Problem Statement 2: 


 
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows: 
 
The moving average sequence has n-k+1 elements as shown below. 
 
The moving averages with k=4 of a ten-value sequence (n=10) is shown below 
 
i 1  2  3  4  5  6  7  8  9 10  ===== == == == == == == == == == ==  Input 10 20 30 40 50 60 70 80 90 100  y1      25 = (10+20+30+40)/4  y2      35 = (20+30+40+50)/4  y3      45 = (30+40+50+60)/4  y4 55 = (40+50+60+70)/4 y5 65 = (50+60+70+80)/4 y6 75 = (60+70+80+90)/4 y7 85 = (70+80+90+100)/4 
 
 
Thus, the moving average sequence has n-k+1=10-4+1=7 values. 

In [ ]:
'''ip = input("Enter the sequence : ")
input_seq = np.fromstring(ip, dtype=int, sep=',')

k = int(input("Enter a value for k, k being less than the number of elements in input sequence : "))

avg =[]
sum = 0

for x in range(0, (len(input_seq)-k+1)):
    for y in range(x, (x+k)):
        sum = sum+input_seq[y]
        a = sum/k
    sum=0
    avg.append(a)

print(avg)
'''

In [4]:
def moving_avg(ip,k):
    #calculating the lenght of the input sequence n
    ip_len = ip.shape[0]
    
    #Output array shape with n-k+1
    op_array = np.zeros(ip_len-k+1)
    
    for i in range(k, ip_len+1):
        op_array[i-k] = ip[i-k:i].mean()
        
    return op_array    
    

In [5]:
ip_seq = input("Enter the sequence : ")
input_seq = np.fromstring(ip_seq, dtype=int, sep=',')

k = int(input("Enter a value for k, k being less than the number of elements in input sequence : "))

ma = moving_avg(input_seq, k)

print("Moving Average of the sequence with k value = {} is : {}" .format(k, ma))

Enter the sequence : 10,20,30,40,50,60,70,80,90,100
Enter a value for k, k being less than the number of elements in input sequence : 4
Moving Average of the sequence with k value = 4 is : [25. 35. 45. 55. 65. 75. 85.]
